# Enhanced Multi-Modal Model Configuration
# Configuration for transformer + ConvLSTM + CrossModalFusion architecture

defaults:
  - _self_
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

hydra:
  output_subdir: null
  run:
    dir: .
  job:
    chdir: false

environment:
  seed: 250104
  device: 'cuda'
  data_root: '/mmfs1/home/hl545/ap/data/datasets'
  save_root: '/mmfs1/home/hl545/ap/results'


experiment:
  experiment_name: 'default'
  phase: 'train'  # 'train' or 'test'
  batch_size: 1
  num_workers: 0
  enable_memory_cache: false
  enable_undersampling: false
  num_subsample: 3
  subsample_index: 0
  enable_oversampling: false
  num_oversample: 13
  apply_pos_weight: false

data:
  dataset_name: 'three_twelve_to_one'
  sdo_wavelengths:
    - '193'
    - '211'
    - 'magnetogram'
  sdo_image_size: 64
  sdo_sequence_length: 28
  input_variables:
    - 'Bx_GSE_GSM_nT' #
    - 'By_GSM_nT' #
    - 'Bz_GSM_nT' #
    - 'B_Magnitude_of_Avg_Field_Vector_nT' #
    - 'Plasma_Flow_Speed_km_s' #
    - 'Proton_Density_n_cm3' #
    - 'Proton_Temperature_K' #
    - 'Kp_Index' #
    - 'ap_Index_nT' #
    - 'DST_Index_nT' #
    - 'f10_7_Index_sfu' #
    - 'Sunspot_Number_R' #
    # - 'Bx_GSE'
    # - 'By_GSM'
    # - 'Bz_GSM'
    # - 'B_magnitude'
    # - 'Flow_speed'
    # - 'Proton_density'
    # - 'Temperature'
    # - 'Kp_index'
    # - 'ap_index'
    # - 'DST_index'
    # - 'f107_index'
    # - 'R_sunspot'
  input_sequence_length: 56
  split_index: 80
  target_variables:
    - 'ap_Index_nT' #
  target_sequence_length: 8
  target_day: 1

model:
  transformer_d_model: 256
  transformer_nhead: 8
  transformer_num_layers: 3
  transformer_dim_feedforward: 512
  transformer_dropout: 0.1

  convlstm_input_channels: 3
  convlstm_hidden_channels: 64
  convlstm_kernel_size: 3
  convlstm_num_layers: 2

  fusion_num_heads: 4
  fusion_dropout: 0.1

training:
  loss_type: 'mse'  # 'mse' or 'mae'
  optimizer: 'adam'  # 'adam' or 'sgd'
  learning_rate: 0.0002
  report_freq: 1000
  num_epochs: 100
  model_save_freq: 20

validation:
  checkpoint_path: /home/hl545/ap/results/wulver_mm_class/checkpoint/model_epoch50.pth
  output_dir: /home/hl545/ap/results/wulver_mm_class/epoch_050