# Enhanced Multi-Modal Model Configuration
# Configuration for transformer + ConvLSTM + CrossModalFusion architecture

defaults:
  - _self_
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

hydra:
  output_subdir: null
  run:
    dir: .
  job:
    chdir: false

environment:
  data_root: '/Users/eunsupark/ap-project/data/datasets'

data:
  dataset_name: 'two_twelve_to_one'
  image_size: 64
  sdo_wavelengths:
   - '193'
   - '211'
   - 'magnetogram'
  num_sdo_wavelengths: 3
  sdo_sequence_length: 40
  sdo_image_size: 64
  split_index: 80
  input_variables:
    - 'Bx_GSE_GSM_nT' #
    - 'By_GSM_nT' #
    - 'Bz_GSM_nT' #
    - 'B_Magnitude_of_Avg_Field_Vector_nT' #
    - 'Plasma_Flow_Speed_km_s' #
    - 'Proton_Density_n_cm3' #
    - 'Proton_Temperature_K' #
    - 'Kp_Index' #
    - 'ap_Index_nT' #
    - 'DST_Index_nT' #
    - 'f10_7_Index_sfu' #
    - 'Sunspot_Number_R' #
  num_input_variables: 12
  input_sequence_length: 80
  target_variables:
    - 'ap_Index_nT' #
  num_target_variables: 1
  target_sequence_length: 40
